/**
 * Created by xdj on 2017/4/24.
 */
export const LOGIN_OPEN_CHANGE = 'LOGIN_OPEN_CHANGE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RECEIVE = 'LOGIN_RECEIVE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE';
export const LOGIN_USER_IS_NULL = "LOGIN_USER_IS_NULL";
export const LOGIN_PWD_IS_NULL = "LOGIN_PWD_IS_NULL";

export const MAIN_LOAD_HTML = "MAIN_LOAD_HTML";
export const MAIN_LOAD_HTML_REQUEST = "MAIN_LOAD_HTML_REQUEST";
export const MAIN_LOAD_HTML_RECEIVE = "MAIN_LOAD_HTML_RECEIVE";
export const MAIN_LOAD_HTML_ERROR = "MAIN_LOAD_HTML_ERROR";

// export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
// export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
// export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
