/**
 * Created by xdj on 2017/4/24.
 */

export const MAIN_MSG_OPEN = "MAIN_MSG_OPEN";
export const MAIN_MSG_CLOSE = "MAIN_MSG_CLOSE";

export const NOT_LOGIN = "NOT_LOGIN";
export const LOGIN_OPEN_CHANGE = 'LOGIN_OPEN_CHANGE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RECEIVE = 'LOGIN_RECEIVE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE';
export const LOGIN_USER_IS_NULL = "LOGIN_USER_IS_NULL";
export const LOGIN_PWD_IS_NULL = "LOGIN_PWD_IS_NULL";

export const MAIN_LOAD_HTML = "MAIN_LOAD_HTML";
export const MAIN_LOAD_HTML_REQUEST = "MAIN_LOAD_HTML_REQUEST";
export const MAIN_LOAD_HTML_RECEIVE = "MAIN_LOAD_HTML_RECEIVE";
export const MAIN_LOAD_HTML_ERROR = "MAIN_LOAD_HTML_ERROR";

export const ADD_MD_OPEN_CHANGE = "ADD_MD_OPEN_CHANGE";
export const ADD_MD_INPUT_CHANGE = "ADD_MD_INPUT_CHANGE";
export const ADD_MD_NAME_IS_NULL = "ADD_MD_NAME_IS_NULL";
export const ADD_MD_PROJECT_IS_NULL = "ADD_MD_PROJECT_IS_NULL";
export const ADD_MD_REQUEST = "ADD_MD_REQUEST";
export const ADD_MD_RECEIVE = "ADD_MD_RECEIVE";
export const ADD_MD_ERROR = "ADD_MD_ERROR";

export const NAV_OPEN_CHANGE = "NAV_OPEN_CHANGE";
export const NAV_LOAD = "NAV_LOAD";
export const NAV_LOAD_REQUEST = "NAV_LOAD_REQUEST";
export const NAV_LOAD_RECEIVE  = "NAV_LOAD_RECEIVE";
export const NAV_LOAD_ERROR = "NAV_LOAD_ERROR";

export const COOMON_FETCH_ERROR = "COOMON_FETCH_ERROR";

